# Generated by Django 6.0 on 2025-12-16 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Unique identifier for the PC/client', max_length=255, unique=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True, help_text='Last time worker sent heartbeat')),
                ('is_active', models.BooleanField(default=True, help_text='Whether worker is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Worker',
                'verbose_name_plural': 'Client Workers',
                'db_table': 'client_workers',
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('banner', models.URLField(blank=True, help_text='URL to the game banner/image (from RAWG API)', max_length=500, null=True)),
                ('save_file_location', models.CharField(help_text='Path to the save file location', max_length=500)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'db_table': 'games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SimpleUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
            ],
            options={
                'verbose_name': 'Simple User',
                'verbose_name_plural': 'Simple Users',
                'db_table': 'simple_users',
            },
        ),
        migrations.CreateModel(
            name='OperationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('save', 'Save'), ('load', 'Load')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('local_save_path', models.CharField(help_text='Local save file path', max_length=500)),
                ('save_folder_number', models.IntegerField(blank=True, help_text='Optional save folder number', null=True)),
                ('result_data', models.JSONField(blank=True, help_text='Operation result data', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if operation failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_worker', models.ForeignKey(blank=True, help_text='Client worker assigned to this operation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SaveNLoad.clientworker')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaveNLoad.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaveNLoad.simpleusers')),
            ],
            options={
                'verbose_name': 'Operation Queue',
                'verbose_name_plural': 'Operation Queue',
                'db_table': 'operation_queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaveFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_number', models.IntegerField(help_text='Save folder number (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_folders', to='SaveNLoad.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_folders', to='SaveNLoad.simpleusers')),
            ],
            options={
                'verbose_name': 'Save Folder',
                'verbose_name_plural': 'Save Folders',
                'db_table': 'save_folders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'game', '-created_at'], name='save_folder_user_id_e922e6_idx')],
                'unique_together': {('user', 'game', 'folder_number')},
            },
        ),
    ]
