# Generated by Django 6.0 on 2025-12-20 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Unique identifier for the PC/client', max_length=255, unique=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True, help_text='Last time worker sent heartbeat')),
                ('is_active', models.BooleanField(default=True, help_text='Whether worker is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Worker',
                'verbose_name_plural': 'Client Workers',
                'db_table': 'client_workers',
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('banner', models.URLField(blank=True, help_text='URL to the game banner/image (from RAWG API)', max_length=500, null=True)),
                ('save_file_location', models.CharField(help_text='Path to the save file location', max_length=500)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('pending_deletion', models.BooleanField(default=False, help_text='If True, game is marked for deletion and will be deleted after all FTP cleanup operations complete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'db_table': 'games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SimpleUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
            ],
            options={
                'verbose_name': 'Simple User',
                'verbose_name_plural': 'Simple Users',
                'db_table': 'simple_users',
            },
        ),
        migrations.CreateModel(
            name='OperationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('save', 'Save'), ('load', 'Load'), ('list', 'List'), ('delete', 'Delete'), ('backup', 'Backup'), ('open_folder', 'Open Folder')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('local_save_path', models.CharField(help_text='Local save file path', max_length=500)),
                ('save_folder_number', models.IntegerField(blank=True, help_text='Optional save folder number', null=True)),
                ('smb_path', models.CharField(blank=True, help_text='Full SMB path for the save folder (Windows format with backslashes)', max_length=500, null=True)),
                ('result_data', models.JSONField(blank=True, help_text='Operation result data', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if operation failed', null=True)),
                ('progress_current', models.IntegerField(default=0, help_text='Current progress count (e.g., files processed)')),
                ('progress_total', models.IntegerField(default=0, help_text='Total items to process')),
                ('progress_message', models.CharField(blank=True, help_text='Current progress message', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_worker', models.ForeignKey(blank=True, help_text='Client worker assigned to this operation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SaveNLoad.clientworker')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaveNLoad.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaveNLoad.simpleusers')),
            ],
            options={
                'verbose_name': 'Operation Queue',
                'verbose_name_plural': 'Operation Queue',
                'db_table': 'operation_queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaveFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_number', models.IntegerField(help_text='Save folder number (1-10)')),
                ('smb_path', models.CharField(blank=True, help_text='Full remote path (e.g., username/gamename/save_1) - FTP path format with forward slashes', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_folders', to='SaveNLoad.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_folders', to='SaveNLoad.simpleusers')),
            ],
            options={
                'verbose_name': 'Save Folder',
                'verbose_name_plural': 'Save Folders',
                'db_table': 'save_folders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'game', '-created_at'], name='save_folder_user_id_e922e6_idx')],
                'unique_together': {('user', 'game', 'folder_number')},
            },
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('email', models.EmailField(help_text='Email address the OTP was sent to', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='OTP expiration time')),
                ('is_used', models.BooleanField(default=False, help_text='Whether OTP has been used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to='SaveNLoad.simpleusers')),
            ],
            options={
                'verbose_name': 'Password Reset OTP',
                'verbose_name_plural': 'Password Reset OTPs',
                'db_table': 'password_reset_otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['otp_code', 'is_used', 'expires_at'], name='password_re_otp_cod_a59dab_idx'), models.Index(fields=['user', 'is_used'], name='password_re_user_id_f24bc2_idx')],
            },
        ),
    ]
