# Generated by Django 6.0 on 2025-12-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('banner', models.URLField(blank=True, help_text='URL to the game banner/image (from RAWG API)', max_length=500, null=True)),
                ('save_file_location', models.CharField(help_text='Path to the save file location', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'db_table': 'games',
                'ordering': ['name'],
            },
        ),
    ]
