# Generated by Django 6.0 on 2025-12-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='banner_url',
            field=models.URLField(blank=True, help_text='Original URL to the game banner/image (from RAWG API)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='banner',
            field=models.ImageField(blank=True, help_text='Cached local banner image file', null=True, upload_to='game_banners/'),
        ),
    ]
