# Generated by Django 6.0 on 2025-12-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleusers',
            name='auto_load_on_login',
            field=models.BooleanField(default=False, help_text='Automatically load save games on login'),
        ),
        migrations.AddField(
            model_name='simpleusers',
            name='auto_save_on_file_change',
            field=models.BooleanField(default=False, help_text='Automatically save games when file changes are detected'),
        ),
    ]
