# Generated by Django 6.0 on 2025-12-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
