# Generated by Django 6.0 on 2025-12-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0002_simpleusers_auto_load_on_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleusers',
            name='auto_load_on_login',
        ),
        migrations.RemoveField(
            model_name='simpleusers',
            name='auto_save_on_file_change',
        ),
        migrations.AddField(
            model_name='game',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="If true, game is archived and won't show in available games"),
        ),
    ]
