# Generated by Django 6.0 on 2025-12-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0003_remove_simpleusers_auto_load_on_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_archived',
        ),
    ]
