# Generated by Django 6.0 on 2025-12-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0004_remove_game_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationqueue',
            name='ftp_path',
            field=models.CharField(blank=True, help_text='Full FTP path for the save folder', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='savefolder',
            name='ftp_path',
            field=models.CharField(blank=True, help_text='Full FTP path (e.g., /username/gamename/save_1)', max_length=500, null=True),
        ),
    ]
