# Generated by Django 6.0 on 2025-12-25 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0005_add_path_mappings_to_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientworker',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this worker', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_workers', to='SaveNLoad.simpleusers'),
        ),
    ]
