# Generated by Django 6.0 on 2025-12-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0005_operationqueue_ftp_path_savefolder_ftp_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationqueue',
            name='operation_type',
            field=models.CharField(choices=[('save', 'Save'), ('load', 'Load'), ('list', 'List'), ('delete', 'Delete')], max_length=10),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('email', models.EmailField(help_text='Email address the OTP was sent to', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='OTP expiration time')),
                ('is_used', models.BooleanField(default=False, help_text='Whether OTP has been used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to='SaveNLoad.simpleusers')),
            ],
            options={
                'verbose_name': 'Password Reset OTP',
                'verbose_name_plural': 'Password Reset OTPs',
                'db_table': 'password_reset_otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['otp_code', 'is_used', 'expires_at'], name='password_re_otp_cod_a59dab_idx'), models.Index(fields=['user', 'is_used'], name='password_re_user_id_f24bc2_idx')],
            },
        ),
    ]
