# Generated by Django 6.0 on 2025-12-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0006_alter_operationqueue_operation_type_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationqueue',
            name='progress_current',
            field=models.IntegerField(default=0, help_text='Current progress count (e.g., files processed)'),
        ),
        migrations.AddField(
            model_name='operationqueue',
            name='progress_message',
            field=models.CharField(blank=True, help_text='Current progress message', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='operationqueue',
            name='progress_total',
            field=models.IntegerField(default=0, help_text='Total items to process'),
        ),
    ]
