# Generated by Django 6.0 on 2025-12-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0006_clientworker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientworker',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='operationqueue',
            name='smb_path',
            field=models.CharField(blank=True, help_text="Full remote path for the save folder (FTP format with forward slashes) - legacy name 'smb_path' kept for compatibility", max_length=500, null=True),
        ),
    ]
