# Generated by Django 6.0 on 2025-12-27 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0007_remove_clientworker_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleusers',
            name='pending_deletion',
            field=models.BooleanField(default=False, help_text='If True, user is marked for deletion and will be deleted after all FTP cleanup operations complete'),
        ),
        migrations.AlterField(
            model_name='operationqueue',
            name='game',
            field=models.ForeignKey(blank=True, help_text='Game associated with the operation (null for user deletion operations)', null=True, on_delete=django.db.models.deletion.CASCADE, to='SaveNLoad.game'),
        ),
    ]
