# Generated by Django 6.0 on 2025-12-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0008_simpleusers_pending_deletion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientworker',
            options={'ordering': ['-last_ping_response', '-last_heartbeat'], 'verbose_name': 'Client Worker', 'verbose_name_plural': 'Client Workers'},
        ),
        migrations.AddField(
            model_name='clientworker',
            name='is_offline',
            field=models.BooleanField(default=False, help_text='Explicit offline flag for UI'),
        ),
        migrations.AddField(
            model_name='clientworker',
            name='last_ping_response',
            field=models.DateTimeField(blank=True, help_text='Last time worker called ping endpoint', null=True),
        ),
        migrations.AddField(
            model_name='clientworker',
            name='missed_ping_count',
            field=models.IntegerField(default=0, help_text='Consecutive missed pings'),
        ),
        migrations.AddField(
            model_name='simpleusers',
            name='last_authenticated_request',
            field=models.DateTimeField(blank=True, help_text='Last time user made an authenticated request - used to detect cookie clearing', null=True),
        ),
        migrations.AlterField(
            model_name='clientworker',
            name='last_heartbeat',
            field=models.DateTimeField(auto_now=True, help_text='Last time worker sent heartbeat - DEPRECATED: Use last_ping_response instead'),
        ),
    ]
