# Generated by Django 6.0 on 2025-12-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0009_alter_clientworker_options_clientworker_is_offline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientworker',
            options={'ordering': ['-last_ping_response'], 'verbose_name': 'Client Worker', 'verbose_name_plural': 'Client Workers'},
        ),
        migrations.RemoveField(
            model_name='clientworker',
            name='last_heartbeat',
        ),
    ]
