# Generated by Django 6.0 on 2025-12-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveNLoad', '0011_remove_client_worker_and_operation_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savefolder',
            name='smb_path',
            field=models.CharField(blank=True, help_text='Full remote path (e.g., username/gamename/save_1) - Remote path format with forward slashes', max_length=500, null=True),
        ),
    ]
