"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Application version - fetched from GitHub or local version.txt file
# Can override GitHub URL via VERSION_GITHUB_URL environment variable
# Priority: GitHub URL > local version.txt > error message if both fail
from SaveNLoad.utils.version_utils import get_app_version
APP_VERSION = get_app_version(
    base_dir=BASE_DIR,
    github_url=os.getenv('VERSION_GITHUB_URL')
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Production: LAN access (localhost + local network)
# For local production deployment accessible via LAN (192.168.88.0/24)
if not DEBUG:
    # Allow localhost and LAN IPs via environment variable
    # Set ALLOWED_HOSTS in .env as comma-separated values to restrict
    # If not set, allows all hosts (suitable for local-only deployment)
    allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
    if allowed_hosts_env:
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',')]
    else:
        # Default: Allow all hosts for local LAN deployment (192.168.88.0/24)
        # This is safe for local-only deployment where you control the network
        ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',  # Use WhiteNoise for static files in production
    'SaveNLoad',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'SaveNLoad.context_processors.app_version',
            ],
        },
    },
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # Removed AuthenticationMiddleware - using custom session-based auth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
    }
}

# Redis Configuration
REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.getenv('REDIS_PORT', 6379))
REDIS_DB = int(os.getenv('REDIS_DB', 0))
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', None)
REDIS_URL = os.getenv('REDIS_URL', f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# WhiteNoise configuration for production static file serving
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# WhiteNoise configuration (LAN deployment)
# WhiteNoise middleware serves static files automatically
# Media files are served via static() helper in urls.py (appropriate for LAN)
WHITENOISE_AUTOREFRESH = True  # Auto-refresh for development/LAN

# Media files (user uploads)
MEDIA_URL = '/media/'  # Add leading slash to match URL patterns
MEDIA_ROOT = BASE_DIR / 'media'

# Email Configuration (Gmail SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('GMAIL_USER')  # Your Gmail address
EMAIL_HOST_PASSWORD = os.getenv('GMAIL_APP_PASSWORD')  # Gmail App Password (not regular password)
DEFAULT_FROM_EMAIL = os.getenv('GMAIL_USER', 'noreply@savenload.com')

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model (not using Django's auth system)
# AUTH_USER_MODEL = 'SaveNLoad.User'  # Removed - using custom session auth

# CSRF Protection Settings
# For local production (no HTTPS), keep secure cookies disabled
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'  # Set to True only with HTTPS
CSRF_COOKIE_HTTPONLY = False  # Must be False for AJAX to work
CSRF_COOKIE_SAMESITE = 'Lax'  # Prevents CSRF attacks while allowing AJAX
CSRF_USE_SESSIONS = False  # Use cookie-based CSRF tokens
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'  # Default CSRF failure view

# Security Settings for Production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SECURE = False  # Set to True only with HTTPS
    SESSION_COOKIE_SAMESITE = 'Lax'

# Permissions-Policy header configuration
# Disable experimental/unsupported features to avoid browser warnings
# These features are not needed for LAN deployment
PERMISSIONS_POLICY = {
    # Disable problematic experimental features that cause browser warnings
    'browsing-topics': [],
    'run-ad-auction': [],
    'join-ad-interest-group': [],
    'private-state-token-redemption': [],
    'private-state-token-issuance': [],
    'private-aggregation': [],
    'attribution-reporting': [],
}

# Cross-Origin-Opener-Policy header
# Disable for LAN deployment (HTTP) to avoid browser warnings
# Only needed for HTTPS deployments with cross-origin requirements
SECURE_CROSS_ORIGIN_OPENER_POLICY = None



# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'suppress_worker_polling': {
            '()': 'SaveNLoad.utils.logging_utils.SuppressEndpointFilter',
            'endpoints': ['/api/client/pending/'],
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['suppress_worker_polling'],
        },
    },
    'loggers': {
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Also filter django.request to be safe, though django.server usually handles the access logs
        'django.request': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
